CREATE TABLE EMPLOYEE
(
	EMPLOYEE_ID      VARCHAR(10) PRIMARY KEY,
    EMPLOYEE_NAME    VARCHAR(10)
)
;

INSERT INTO EMPLOYEE
SELECT '10000','김경한';

INSERT INTO EMPLOYEE
SELECT '10001','박병천';

INSERT INTO EMPLOYEE
SELECT '10002','박성용';

INSERT INTO EMPLOYEE
SELECT '10003','이재혁';

INSERT INTO EMPLOYEE
SELECT '10004','이한용';

INSERT INTO EMPLOYEE
SELECT '10005','장준우';

INSERT INTO EMPLOYEE
SELECT '10006','정재엽';

INSERT INTO EMPLOYEE
SELECT '10007','주형진';